<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BetterCharacterRelics</AssemblyName>
    <RootNamespace>BetterCharacterRelics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="CompatibilityTarget" Value="$(GameVersion)" />
    <EmbeddedResource Include="../tests/snapshots/$(GameVersion)/vanilla-il.txt" LogicalName="vanilla-il.txt" Condition="Exists('../tests/snapshots/$(GameVersion)/vanilla-il.txt')" />
  </ItemGroup>
</Project>
