<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <HarmonyReference>../../../HextechRunes/versioned-dll-backups/0.110.0/game-refs/0Harmony.dll</HarmonyReference>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyReference)</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
